[package]
name = "binary"
description = "Defines a specification and trait for external binaries"
version = "0.0.0"
edition = "2021"

[features]
default = ["download"]
download = ["http-utils"]
download-zip = ["download", "archive-utils/zip"]
download-tar = ["download", "archive-utils/tar"]
download-tar-gz = ["download-tar", "archive-utils/tar-gz"]
download-tar-xz = ["download-tar", "archive-utils/tar-xz"]

[dependencies]
common = { path = "../common" }
semver = "1.0.12"
which = "4.2.2"

archive-utils = { path = "../archive-utils", optional = true }
http-utils = { path = "../http-utils", optional = true }
