[package]
name = "stencila-schema"
version = "1.16.1"
edition = "2018"
description = "Rust bindings for Stencila Schema"
authors = ["Nokome Bentley <nokome@stenci.la>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://schema.stenci.la"
repository = "https://github.com/stencila/stencila"
keywords = ["schema", "executable", "documents"]

[dependencies]
chrono = "0.4.22"
derivative = "2.2.0"
float-cmp = "0.9.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
serde_with = "2.0.0"
strum = { version = "0.24.0", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"
