[package]
name = "schema"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-html-trait = { path = "../codec-html-trait" }
codec-losses = { path = "../codec-losses" }
codec-markdown-trait = { path = "../codec-markdown-trait" }
codec-text-trait = { path = "../codec-text-trait" }
common = { path = "../common" }
monostate = "0.1.9"
node-store = { path = "../node-store" }
node-store-derive = { path = "../node-store-derive" }
node-strip = { path = "../node-strip" }
smol_str = "0.1.24"

[dev-dependencies]
common-dev = { path = "../common-dev" }
