[package]
name = "schema"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
monostate = "0.1"
node-store = { path = "../node-store" }
node-store-derive = { path = "../node-store-derive" }
similar = { version = "2.2.1", features = ["unicode"] }
smol_str = "0.1.24"

[dev-dependencies]
common-dev = { path = "../common-dev" }
codec-text = { path = "../codec-text" }
node-strip = { path = "../node-strip" }
