[package]
name = "schema"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-html-derive = { path = "../codec-html-derive" }
codec-html-traits = { path = "../codec-html-traits" }
codec-losses = { path = "../codec-losses" }
codec-text-derive = { path = "../codec-text-derive" }
codec-text-traits = { path = "../codec-text-traits" }
common = { path = "../common" }
monostate = "0.1.9"
node-store = { path = "../node-store" }
node-store-derive = { path = "../node-store-derive" }
node-strip = { path = "../node-strip" }
node-strip-derive = { path = "../node-strip-derive" }
smol_str = "0.1.24"

[dev-dependencies]
common-dev = { path = "../common-dev" }
