[package]
description = "A kernel that delegates to a Jupyter kernel"
edition = "2021"
name = "kernel-jupyter"
version = "0.0.0"

[features]
default = ["zmq/vendored"]

[dependencies]
chrono = {version = "0.4.19", features = ["serde"]}
codec-ipynb = {path = "../codec-ipynb", version = "0.0.0"}
defaults = "0.2.0"
derivative = "2.2.0"
dirs = "4.0.0"
glob = "0.3.0"
hex = "0.4.3"
hmac = "0.11.0"
kernel = {path = "../kernel", version = "0.0.0"}
key-utils = {path = "../key-utils", version = "0.0.0"}
once_cell = "1.8.0"
path-slash = "0.1.4"
portpicker = "0.1.1"
reqwest = "0.11.6"
serde = "1.0.130"
serde_json = "1.0.68"
serde_with = "1.11.0"
sha2 = "0.9.8"
tokio = {version = "1.12.0", features = ["full"]}
tracing = "0.1.29"
uuid-utils = {path = "../uuid-utils", version = "0.0.0"}
zmq = {version = "0.9.2", default-features = false}

[dev-dependencies]
test-utils = {path = "../test-utils", version = "0.0.0"}
