[package]
name = "kernel-jupyter"
description = "A kernel that delegates to a Jupyter kernel"
version = "0.0.0"
edition = "2021"

[dependencies]
dirs = "4.0.0"
kernel = { path = "../kernel", version = "0.0.0" }
once_cell = "1.8.0"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["rt", "macros"] }
test-utils = { path = "../test-utils", version = "0.0.0" }
