[package]
name = "cli-utils"
description = "Utilities for command line interfaces"
version = "0.0.0"
edition = "2021"

[features]
default = []
pretty = ["syntect", "termimad", "urlencoding"]
progress = ["events", "linya"]
interact = ["rustyline", "rustyline-derive"]

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
color-eyre = "0.6.1"
common = { path = "../common" }
events = { path = "../events", optional = true }
linya = { version = "0.2.1", optional = true }
rustyline = { version = "9.0.0", optional = true }
rustyline-derive = { version = "0.6.0", optional = true }
structopt = { version = "0.3.25", features = ["wrap_help"] }
syntect = { version = "4.6.0", optional = true }
termimad = { version = "0.20.0", optional = true }
tracing-subscriber = "0.3.6"
urlencoding = { version = "2.1.0", optional = true }
