api = "0.6"

[buildpack]
id = "stencila/node"
version = "0.1.0"
name = "Stencila Node.js Buildpack"
keywords = ["nodejs", "node", "npm", "npx"]
homepage = "https://github.com/stencila/stencila/tree/HEAD/rust/buildpack-node"

[[buildpack.licenses]]
type = "Apache-2.0"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
