[package]
name = "buildpack-node"
description = "A Cloud Native Buildpack for Node.js"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-node = { path = "../binary-node", version = "0.0.0" }
buildpack = { path = "../buildpack", version = "0.0.0" }
serde = "1.0.130"
serde_json = "1.0.75"
