[package]
name = "buildpack-node"
description = "A Cloud Native Buildpack for Node.js"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-node = { path = "../binary-node" }
buildpack = { path = "../buildpack" }
common = { path = "../common" }
