[package]
name = "binary-pandoc"
description = "A binary specification for Pandoc"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", features = [
    "download-zip",
    "download-tar-gz",
] }
