[package]
name = "cloud"
version = "0.0.0"
edition = "2021"

[dependencies]
cli-utils = { path = "../cli-utils", features = ["pretty"] }
common = { path = "../common" }
fs-utils = { path = "../fs-utils" }
http-utils = { path = "../http-utils" }
key-utils = { path = "../key-utils" }
webbrowser = "0.7.1"
