[package]
name = "kernel-micro"
description = "A trait for minimal, lightweight, 'microkernels'"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries" }
kernel = { path = "../kernel" }
nix = "0.24.2"
