[package]
name = "node-pointer"
description = "Pointers to nodes within Stencila documents"
version = "0.0.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
node-address = { path = "../node-address", version = "0.0.0" }
node-dispatch = { path = "../node-dispatch", version = "0.0.0" }
node-transform = { path = "../node-transform", version = "0.0.0" }
stencila-schema = "1.14.0" 
