[package]
name = "node-pointer"
description = "Pointers to nodes within Stencila documents"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
node-address = { path = "../node-address" }
node-dispatch = { path = "../node-dispatch" }
node-transform = { path = "../node-transform" }
stencila-schema = { path = "../schema" }
