[package]
name = "node-pointer"
description = "Pointers for performing actions on nodes in Stencila document trees"
version = "0.0.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
node-address = { path = "../node-address", version = "0.0.0" }
node-dispatch = { path = "../node-dispatch", version = "0.0.0" }
node-patch = { path = "../node-patch", version = "0.0.0" }
stencila-schema = "1.12.0"
