[package]
name = "binaries"
description = "Utilities for managing and calling external binaries"
version = "0.0.0"
edition = "2021"

[features]

# The CLI is not enabled by default to avoid extra dependencies for crates
# that only want to use `require()`.
cli = ["cli-utils", "structopt"]

[dependencies]
cli-utils = { path = "../cli-utils", version = "0.0.0", optional = true }
defaults = "0.2.0"
dirs = "4.0.0"
eyre = "0.6.5"
flate2 = "1.0.22"
itertools = "0.10.1"
once_cell = "1.8.0"
regex = "1.5.4"
reqwest = "0.11.7"
semver = "1.0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
structopt = { version = "0.3.25", optional = true }
tar = "0.4.37"
tokio = { version = "1.13.0", features = ["process", "macros"] }
tracing = "0.1.29"
url = "2.2.2"
which = "4.2.2"
xz2 = "0.1.6"
zip = "0.5.13"

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
