[package]
name = "test-snaps"
description = "Utility functions for snapshot testing"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
insta = { version = "1.19.1", features = ["json", "glob", "redactions"] }
stencila-schema = { path = "../schema" }
test-utils = { path = "../test-utils" }
