[package]
name = "test-snaps"
description = "Utility functions for snapshot testing"
version = "0.0.0"
edition = "2021"

[dependencies]
insta = { version = "1.8.0", features = ["glob"] }
serde_json = "1.0.69"
stencila-schema = "1.12.0"
test-utils = { path = "../test-utils", version = "0.0.0" }
