[package]
name = "parser-calc"
version = "0.0.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
