[package]
name = "css-utils"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
lightningcss = "1.0.0-alpha.35"
nom = "7.1.0"
tailwind-css = { git = "https://github.com/nokome/tailwind-rs", rev = "99c37acd301fbf65357d6ec621a4d4d6a505adcc" }

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
