[package]
name = "parser"
description = "Defines a specification and trait for parsers for semantically analyzing code"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
graph-triples = { path = "../graph-triples" }
