[package]
name = "provider-gitlab"
description = " A provider for Gitlab"
version = "0.0.0"
edition = "2021"

[dependencies]
archive-utils = { path = "../archive-utils", features = [
    "tar-gz",
] }
provider = { path = "../provider" }
uuids = { path = "../uuids" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
