[package]
name = "codec-person"
description = "A codec for people's names, honorifics and contact details"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
human_name = "1.0.3"

[dev-dependencies]
test-utils = { path = "../test-utils" }
