[package]
name = "parsers"
description = "The set of registered parsers, either built-in, or provided by plugins"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils"]

[dependencies]
common = { path = "../common" }
parser = { path = "../parser" }
formats = { path = "../formats" }

cli-utils = { path = "../cli-utils" , optional = true}

parser-bash = { path = "../parser-bash" , optional = true}
parser-calc = { path = "../parser-calc" , optional = true}
parser-http = { path = "../parser-http" , optional = true}
parser-js = { path = "../parser-js" , optional = true}
parser-json = { path = "../parser-json" , optional = true}
parser-json5 = { path = "../parser-json5" , optional = true}
parser-postgrest = { path = "../parser-postgrest" , optional = true}
parser-prql = { path = "../parser-prql" , optional = true}
parser-python = { path = "../parser-python" , optional = true}
parser-r = { path = "../parser-r" , optional = true}
parser-sql = { path = "../parser-sql" , optional = true}
parser-tailwind = { path = "../parser-tailwind" , optional = true}

[dev-dependencies]
test-utils = { path = "../test-utils" }
