[package]
name = "parsers"
description = "The set of registered parsers, either built-in, or provided by plugins"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils", "structopt"]

[dependencies]
parser = { path = "../parser", version = "0.0.0" }
formats = { path = "../formats", version = "0.0.0" }
once_cell = "1.9.0"

cli-utils = { path = "../cli-utils", version = "0.0.0" , optional = true}
structopt = { version = "0.3.25" , optional = true}

# See note in root Cargo.toml for why this is excluded for now
# parser-bash = { path = "../parser-bash", version = "0.0.0" , optional = true}
parser-calc = { path = "../parser-calc", version = "0.0.0" , optional = true}
parser-js = { path = "../parser-js", version = "0.0.0" , optional = true}
parser-py = { path = "../parser-py", version = "0.0.0" , optional = true}
parser-r = { path = "../parser-r", version = "0.0.0" , optional = true}
parser-rust = { path = "../parser-rust", version = "0.0.0" , optional = true}
parser-ts = { path = "../parser-ts", version = "0.0.0" , optional = true}

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
