[package]
name = "parsers"
description = "The set of registered parsers, either built-in, or provided by plugins"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils", "structopt"]

[dependencies]
common = { path = "../common" }
parser = { path = "../parser" }
formats = { path = "../formats" }

cli-utils = { path = "../cli-utils" , optional = true}
structopt = { version = "0.3.25" , optional = true}

parser-bash = { path = "../parser-bash" , optional = true}
parser-calc = { path = "../parser-calc" , optional = true}
parser-js = { path = "../parser-js" , optional = true}
parser-py = { path = "../parser-py" , optional = true}
parser-r = { path = "../parser-r" , optional = true}
parser-rust = { path = "../parser-rust" , optional = true}
parser-ts = { path = "../parser-ts" , optional = true}

[dev-dependencies]
test-utils = { path = "../test-utils" }
