[package]
name = "cron-utils"
description = "Utilities for creating cron schedules"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.1"
cron = "0.9.0"
eyre = "0.6.6"
nom = "7.1.0"
once_cell = "1.10.0"
