[package]
name = "cron-utils"
description = "Utilities for creating cron schedules"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono-tz = "0.6.1"
common = { path = "../common" }
cron = "0.9.0"
nom = "7.1.0"
