[package]
name = "provider"
description = "A trait and specification for third-party providers of data"
version = "0.0.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
serde = { version = "1.0.130", features = ["derive"] }
