[package]
name = "provider"
description = "A trait and specification for third-party providers of data"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
eyre = "0.6.5"
node-address = { path = "../node-address", version = "0.0.0" }
serde = { version = "1.0.130", features = ["derive"] }
stencila-schema = "1.16.1"
