[package]
name = "node-transform"
description = "Transform a Stencila document node to another node type"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
codec-txt = { path = "../codec-txt" }
stencila-schema = { path = "../schema" }
