[package]
name = "codec-pdf"
description = "A codec for PDF files"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries" }
chromiumoxide = { version = "0.3.4", features = ["tokio-runtime"] }
codec-html = { path = "../codec-html" }
codec = { path = "../codec" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
