[package]
name = "codec-pdf"
description = "A codec for PDF files"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries", version = "0.0.0" }
chromiumoxide = { version = "0.3.2", features = ["tokio-runtime"] }
codec-html = { path = "../codec-html", version = "0.0.0" }
codec = { path = "../codec", version = "0.0.0" }
futures = "0.3.18"
tokio = { version = "1.13.0", features = ["macros"] }

[dev-dependencies]
tempfile = "3.2.0"
