[package]
name = "parser-postgrest"
version = "0.0.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
nom = "7.1.0"
nom-recursive = "0.4.0"
nom_locate = "4.0.0"

[dev-dependencies]
test-utils = { path = "../test-utils" }
