matrix:
  include:
    # Test Typescript package
    - stage: test
      language: node_js
      node_js: '12'

      script:
        - npm run lint
        - npm run build
        - npm run test:cover
        - npm run docs

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF ts

    # Test Python package
    - stage: test
      language: python
      python: '3.7'
      dist: xenial

      before_install:
        - cd py

      install:
        - make setup

      script:
        - make lint
        - make test
        - make build
        - make docs

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py

    # Test R package
    - stage: test
      language: r
      r: release

      before_install:
        - cd r

      script:
        - make lint
        - make test
        - make build
        - make docs

      after_success:
        - Rscript -e 'covr::codecov()'

    # The following deployment jobs will only run if all of
    # the above test jobs have passed

    # Deploy NPM package and create a release
    - stage: deploy
      language: node_js
      node_js: '12'

      script:
        - npm run build
        - npm run docs

      deploy:
        # Deploy a new version of NPM package and create a Github release
        # This creates a new version tag, which will then trigger the
        # following deploy jobs for other language packages.
        - provider: script
          skip_cleanup: true
          script: npx semantic-release

        # Commit package documentation to gh-pages
        # Main documentation is deployed using Netlify
        - provider: script
          skip-cleanup: true
          script: |
            . .travis/funcs.sh
            checkout_pages

            # Main index page
            cp public/packages-index.html index.html
            # Typescript API docs
            cd ts
            mv docs docs-new
            git rm -rf docs
            mv docs-new docs
            git add --all docs

            commit_and_push_pages "docs(Typescript): Update"
          on:
            branch: master
            tags: true

    # Deploy Python package
    - stage: deploy
      language: python
      python: '3.7'
      dist: xenial

      before_install:
        - cd py

      install:
        - make setup

      script:
        - make docs

      deploy:
        - provider: pypi
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true

        - provider: script
          skip-cleanup: true
          script: |
            . .travis/funcs.sh
            checkout_pages

            mv docs docs-new
            git rm -rf docs
            mv docs-new docs
            git add --all docs

            commit_and_push_pages "docs(Python): Update"
          on:
            branch: master
            tags: true

    # Deploy R package
    - stage: deploy
      language: r
      r: release

      before_install:
        - cd r

      script:
        - make docs

      deploy:
        - provider: script
          skip-cleanup: true
          script: |
            . .travis/funcs.sh
            checkout_pages

            mv docs docs-new
            git rm -rf docs
            mv docs-new docs
            git add --all docs

            commit_and_push_pages "docs(R): Update"
          on:
            branch: master
            tags: true
