strategy:
  matrix:
    linux:
      image_name: ubuntu-latest
    mac:
      image_name: macOS-latest
    windows:
      image_name: windows-latest

pool:
  vmImage: $(image_name)

steps:
  # Install Rust on Linux and macOS.
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: 'Install rust (*nix)'
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

  # Install Rust on Windows.
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --profile minimal --default-toolchain stable --default-host x86_64-pc-windows-msvc
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: 'Install rust (windows)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')
