trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
  drafts: false
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
    displayName: Install Node.js

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm

  - script: npm ci
    displayName: Install dependencies

  - script: |
      npm run check:themes
      npm run lint
    displayName: Run linting
    failOnStderr: true

  - script: |
      npm run test:unit -- --coverage --ci
      bash <(curl -s https://codecov.io/bash)
    displayName: Run unit tests
    failOnStderr: true

  - script: |
      npm run docs
      npm run test:visual
      npx argos upload test/screenshots/local -T "$ARGOS_TOKEN" -B "$(Build.SourceBranch)" -C "$(Build.SourceVersion)"
    displayName: Run visual regression tests
    condition: and(succeeded(), ne(variables['SAUCE_ACCESS_KEY'], ''), ne(variables['ARGOS_TOKEN'], ''))
    env:
      ARGOS_TOKEN: $(ARGOS_TOKEN)
      SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
      SAUCE_USERNAME: $(SAUCE_USERNAME)

  - script: npm run build
    condition: succeeded()
    displayName: 'Build package'

  - script: ASSET_PATH=/thema/ npm run docs
    condition: succeeded()
    displayName: 'Build documentation site'

  - script: npx semantic-release
    condition: and(succeeded(), eq(variables.isMain, true))
    displayName: Release package & Publish documentation site
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      NPM_TOKEN: $(NPM_TOKEN)
