[workspace]

# DO not include Python and R binding until more developed
members = ["rust/*", "node"]

# Exlcude rust crates in alpha status needing work before they will compile and/or pass tests
exclude = [
    "rust/codec-docx",
    "rust/codec-latex",
    "rust/codec-pandoc",
    "rust/codec-pdf",
    "rust/codec-png",
    "rust/codec-rpng",
    "rust/plugins",
]

[profile.release]
# Settings that help reduce the binary size based on https://github.com/johnthagen/min-sized-rust
lto = true
codegen-units = 1
# Currently, disable `panic = 'abort'` given that it causes the linking error described here
# https://stackoverflow.com/questions/39844260/how-to-use-panic-abort-with-external-dependencies
# because the crate `human_name` specifies `dylib` as one of its library types.
# panic = 'abort'
