[workspace]

# Do not include Node, Python and R binding until more developed
members = ["rust/*"]

# Exclude crates that are experimental or are in process of being deprecated
exclude = [
    "rust/plugins",
    "rust/kernel-deno",
    "rust/kernel-jupyter",
    "rust/parser-rust",
    "rust/parser-ts",
]

[profile.ci]
# Settings aimed at reducing disk usage and improving build times on CI
# At time of writing, these settings produced a ./target/ci that was 5G vs a
# ./target/debug of 15G.
inherits = "dev"
debug = false
strip = true
opt-level = "z"

[profile.release]
# Settings that help reduce the binary size based on https://github.com/johnthagen/min-sized-rust
lto = true
codegen-units = 1
# Currently, disable `panic = 'abort'` given that it causes the linking error described here
# https://stackoverflow.com/questions/39844260/how-to-use-panic-abort-with-external-dependencies
# because the crate `human_name` specifies `dylib` as one of its library types.
# panic = 'abort'
