[workspace]

members = [
    "rust",
    "python"
]

[profile.release]
# Settings that help reduce the binary size based on https://github.com/johnthagen/min-sized-rust
lto = true
codegen-units = 1
panic = 'abort'
