# Redirect from /latest to root
[[redirects]]
  from = "/latest/*"
  to = "/:splat"

# The recommended way to serve JSON-LD is with "Cool URIs"
# and content negotiation. eg. this is how schema.org does it:
#   curl http://schema.org/Person -H "Accept:application/ld+json" -i
# Netlify does not support content negotiation
# (i.e. redirects based on the Accept header)
# Therefore, to provide a URL that fits with
# the norms for for JSON-LD (no file extensions),
# we need to provide a specific route.
[[redirects]]
  from = "/jsonld/*"
  to = "/:splat.jsonld"

# Version redirects
# Unfortunately, given the current URL pattern `v1` etc,
# we can't make this work using placeholders
# (i.e. using `v:number`; placeholders must come after a slash).

[[redirects]]
  from = "/v0/jsonld/*"
  to = "https://unpkg.com/@stencila/schema@0/dist/:splat.jsonld"
  force = true

[[redirects]]
  from = "/v0/*"
  to = "https://unpkg.com/@stencila/schema@0/dist/:splat"
  force = true
