# Redirect from /latest to root
[[redirects]]
  from = "/latest/*"
  to = "/:splat"

# Version redirects
# Unfortunately, given the current URL pattern `v1` etc,
# we can't make this work using placeholders
# (i.e. using `v:number`; placeholders must come after a slash).
# The redirects below for non-existent versions is done
# to avoid a 404 if this setup is forgotten about in the future.

[[redirects]]
  from = "/v0/*"
  to = "https://unpkg.com/@stencila/schema@0/dist/:splat"

[[redirects]]
  from = "/v1/*"
  to = "https://unpkg.com/@stencila/schema@1/dist/:splat"

[[redirects]]
  from = "/v2/*"
  to = "https://unpkg.com/@stencila/schema@2/dist/:splat"

[[redirects]]
  from = "/v3/*"
  to = "https://unpkg.com/@stencila/schema@3/dist/:splat"

[[redirects]]
  from = "/v4/*"
  to = "https://unpkg.com/@stencila/schema@4/dist/:splat"

[[redirects]]
  from = "/v5/*"
  to = "https://unpkg.com/@stencila/schema@5/dist/:splat"
