[package]
name = "path-utils"
description = "Utitlity functions and macros for working with filesystem paths"
version = "0.0.0"
edition = "2021"

[dependencies]
lexiclean = "0.0.1"
path-slash = "0.1.4"
pathdiff = "0.2.1"
