[package]
name = "kernel-node"
description = "A microkernel for Node.js"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries", features = ["binary-node"] }
kernel = { path = "../kernel" }
kernel-micro = { path = "../kernel-micro" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
