[package]
name = "parser-tailwind"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
lightningcss = "1.0.0-alpha.35"
parser = { path = "../parser" }
tailwind-css = { git = "https://github.com/nokome/tailwind-rs", rev = "99c37acd301fbf65357d6ec621a4d4d6a505adcc" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
