[package]
name = "uuids"
description = "Utility types and functions for universally unique identifiers"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
nanoid = "0.4.0"
smartstring = { version = "1.0.1", features = ["serde"] }
