[package]
name = "buildpacks"
description = "Buildpacks for building project container images"
version = "0.0.0"
edition = "2021"

[features]
default = ["cli"]
cli = ["cli-utils"]

[dependencies]
binary-pack = { path = "../binary-pack" }
buildpack = { path = "../buildpack" }
bytes = "1.1.0"
common = { path = "../common" }
hash-utils = { path = "../hash-utils" }
http-utils = { path = "../http-utils" }

cli-utils = { path = "../cli-utils", optional = true, features = [
    "pretty",
] }

buildpack-apt = { path = "../buildpack-apt", optional = true }
buildpack-dockerfile = { path = "../buildpack-dockerfile", optional = true }
buildpack-node = { path = "../buildpack-node", optional = true }
buildpack-python = { path = "../buildpack-python", optional = true }
buildpack-r = { path = "../buildpack-r", optional = true }
buildpack-stencila = { path = "../buildpack-stencila", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
