[package]
name = "buildpacks"
description = "Buildpacks for building project container images"
version = "0.0.0"
edition = "2021"

[features]
default = ["cli", "rkyv-safe"]
rkyv-safe = ["rkyv", "bytecheck"]
cli = ["cli-utils", "structopt"]

[dependencies]
archive-utils = { path = "../archive-utils", version = "0.0.0" }
binary-pack = { path = "../binary-pack", version = "0.0.0" }
buildpack = { path = "../buildpack", version = "0.0.0" }
bytes = "1.1.0"
chrono = "0.4.19"
eyre = "0.6.6"
futures = "0.3.19"
hash-utils = { path = "../hash-utils", version = "0.0.0" }
http-utils = { path = "../http-utils", version = "0.0.0" }
jwalk = "0.6.0"
oci-spec = "0.5.6"
once_cell = "1.9.0"
regex = "1.5.4"
seahash = "4.1.0"
serde_json = "1.0.81"
tokio = { version = "1.13.0", features = ["fs", "macros", "rt-multi-thread"] }
tracing = { version = "0.1.29" }

cli-utils = { path = "../cli-utils", version = "0.0.0", optional = true, features = [
    "pretty",
] }
structopt = { version = "0.3.25", optional = true }

rkyv = { version = "0.7.38", features = ["validation"], optional = true }
bytecheck = { version = "0.6.8", optional = true }

buildpack-apt = { path = "../buildpack-apt", version = "0.0.0", optional = true }
buildpack-dockerfile = { path = "../buildpack-dockerfile", version = "0.0.0", optional = true }
buildpack-node = { path = "../buildpack-node", version = "0.0.0", optional = true }
buildpack-python = { path = "../buildpack-python", version = "0.0.0", optional = true }
buildpack-r = { path = "../buildpack-r", version = "0.0.0", optional = true }
buildpack-sources = { path = "../buildpack-sources", version = "0.0.0", optional = true }
buildpack-stencila = { path = "../buildpack-stencila", version = "0.0.0", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
test-snaps = { path = "../test-snaps", version = "0.0.0" }
