# Defines a CNB builder
# See https://buildpacks.io/docs/reference/config/builder-config/

description = "Stencila CNB builder based on Ubuntu 20.04"

# The buildpacks to include in the builder

[[buildpacks]]
uri = "../../../rust/buildpack-node"

[[buildpacks]]
uri = "../../../rust/buildpack-python"

[[buildpacks]]
uri = "../../../rust/buildpack-r"

# The order in which groups of buildpacks will be tested during detection
# All buildpacks are optional, so they can potentially all be applied to the
# same project.

[[order]]

  [[order.group]]
  id = "stencila/node"
  optional = true

  [[order.group]]
  id = "stencila/python"
  optional = true

  [[order.group]]
  id = "stencila/r"
  optional = true

# The stack to use for the builder

[stack]
id = "stencila.stacks.focal"
run-image = "stencila/run:focal"
build-image = "stencila/build:focal"
