[package]
name = "provider-doi"
description = "Implements the `Provider` trait for DOIs"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-csl = { path = "../codec-csl", version = "0.0.0" }
provider = { path = "../provider", version = "0.0.0" }
reqwest = "0.11.7"
serde_json = "1.0.72"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros"] }
test-utils = { path = "../test-utils", version = "0.0.0" }
