[package]
name = "provider-doi"
description = "Implements the `Provider` trait for DOIs"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-csl = { path = "../codec-csl" }
provider = { path = "../provider" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
