[package]
name = "provider-doi"
description = "Implements the `Provider` trait for DOIs"
version = "0.0.0"
edition = "2021"

[dependencies]
octocrab = "0.13.0"
once_cell = "1.8.0"
node-pointer = { path = "../node-pointer", version = "0.0.0" }
provider = { path = "../provider", version = "0.0.0" }
regex = "1.5.4"
reqwest = "0.11.7"
serde_json = "1.0.72"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros"] }
test-utils = { path = "../test-utils", version = "0.0.0" }
