[package]
name = "node-coerce"
description = "Coerce a JSON value to a Stencila document node"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-date = { path = "../codec-date" }
codec-person = { path = "../codec-person" }
codec = { path = "../codec" }
common = { path = "../common" }
stencila-schema = { path = "../schema" }
utils = { path = "../utils" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
