[package]
name = "buildpack"
description = "Provides Buildpack trait for defining Cloud Native Buildpacks for Stencila"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
fs-utils = { path = "../fs-utils" }
hash-utils = { path = "../hash-utils" }
libcnb = "0.7.0"
tracing-subscriber = "0.3.6"
