[package]
name = "images"
version = "0.0.0"
edition = "2021"

[features]
default = ["cli", "rkyv-safe"]

cli = ["cli-utils"]
rkyv-safe = ["rkyv", "bytecheck"]

[dependencies]
archive-utils = { path = "../archive-utils", features = ["tar-gz", "tar-zst"] }
bytes = "1.1.0"
bytesize = "1.1.0"
common = { path = "../common" }
fs-utils = { path = "../fs-utils" }
gitignore = "1.0.7"
hash-utils = { path = "../hash-utils" }
http-utils = { path = "../http-utils" }
jwalk = "0.6.0"
oci-spec = "0.5.7"
path-utils = { path = "../path-utils" }

cli-utils = { path = "../cli-utils", optional = true, features = ["pretty"] }

rkyv = { version = "0.7.39", features = ["validation"], optional = true }
bytecheck = { version = "0.6.8", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
