[package]
name = "images"
version = "0.0.0"
edition = "2021"

[features]
default = [
    "cli",
    "rkyv-safe",

    "buildpacks/buildpack-apt",
    "buildpacks/buildpack-dockerfile",
    "buildpacks/buildpack-node",
    "buildpacks/buildpack-python",
    "buildpacks/buildpack-r",
    "buildpacks/buildpack-sources",
    "buildpacks/buildpack-stencila",
]

cli = ["cli-utils", "structopt"]
rkyv-safe = ["rkyv", "bytecheck"]

[dependencies]
archive-utils = { path = "../archive-utils", features = [
    "tar-gz",
    "tar-zst",
] }
buildpacks = { path = "../buildpacks" }
bytes = "1.1.0"
bytesize = "1.1.0"
common = { path = "../common" }
gitignore = "1.0.7"
hash-utils = { path = "../hash-utils" }
http-utils = { path = "../http-utils" }
jwalk = "0.6.0"
oci-spec = "0.5.6"
seahash = "4.1.0"

cli-utils = { path = "../cli-utils", optional = true, features = [
    "pretty",
] }
structopt = { version = "0.3.25", optional = true }

rkyv = { version = "0.7.38", features = ["validation"], optional = true }
bytecheck = { version = "0.6.8", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
test-snaps = { path = "../test-snaps" }
