[package]
name = "hash-utils"
description = "Utility functions and macros for working with hashing algorithms"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
hmac = "0.12.1"
seahash = "4.1.0"
sha2 = "0.10.0"
