[package]
name = "parser-bash"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
tree-sitter-bash = { git = "https://github.com/tree-sitter/tree-sitter-bash", rev = "e31399d15473bd2bbb6007e092fe2309e74c94f9" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
