[package]
name = "parser-bash"
version = "0.0.0"
edition = "2021"

[dependencies]
once_cell = "1.9.0"
parser-treesitter = { path = "../parser-treesitter", version = "0.0.0" }
tree-sitter-bash = { git = "https://github.com/nokome/tree-sitter-bash", rev = "e31399d15473bd2bbb6007e092fe2309e74c94f9" }

[dev-dependencies]
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }