[package]
name = "kernel-r"
description = "A microkernel for R"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries", version = "0.0.0", features = ["binary-r"] }
kernel = { path = "../kernel", version = "0.0.0" }
kernel-micro = { path = "../kernel-micro", version = "0.0.0" }

[dev-dependencies]
tokio = { version = "1.13.0", features = ["macros", "time"] }
test-utils = { path = "../test-utils", version = "0.0.0" }
once_cell = "1.9.0"
