[package]
name = "node-address"
description = "Addresses for referring to nodes in Stencila document trees"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
schemars = "0.8.10"
thiserror = "1.0.31"
