[package]
name = "node-address"
description = "Addresses for referring to nodes in Stencila document trees"
version = "0.0.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
derive_more = "0.99.17"
eyre = "0.6.5"
schemars = "0.8.8"
serde = "1.0.130"
strum = { version = "0.23.0", features = ["derive"] }
thiserror = "1.0.30"
