[package]
name = "binary-chrome"
description = "A binary specification for Chrome/Chromium"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", version = "0.0.0", features = ["download-zip"] }
