[package]
name = "kernel-sql"
version = "0.0.0"
edition = "2021"

[dependencies]
arrow = "21.0.0"
duckdb = { version = "0.5.0", features = ["bundled"] }
events = { path = "../events" }
kernel = { path = "../kernel" }
prql-compiler = "0.2.6"
parser-sql = { path = "../parser-sql" }
sqlx = { version = "0.6.1", features = [
    "runtime-tokio-rustls",
    "any",
    # The `mysql` feature is not included because, at the time of writing,
    # it caused a compile error `error[E0277]: (dyn functions::Function + 'static)` cannot be sent between threads safely`
    "sqlite",
    "postgres",

    "chrono"
] }

[dev-dependencies]
test-utils = { path = "../test-utils" }
