[package]
name = "test-props"
description = "Utility functions and strategies for property testing"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.10.1"
proptest = "1.0.0"
stencila-schema = "1.15.0"
