[package]
name = "server-next"
version = "0.0.0"
edition = "2021"

[features]
default = ["cli"]
cli = ["cli-utils"]

[dependencies]
axum = "0.5.5"
common = { path = "../common" }
mime_guess = "2.0.4"
portpicker = "0.1.1"
rust-embed = { version = "6.4.0", features = ["compression"] }
tower-http = { version = "0.3.3", features = ["trace"] }

cli-utils = { path = "../cli-utils", features = ["pretty"], optional = true }
