[package]
name = "codec-csl"
description = "A codec for Citation Style Language (CSL) JSON"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec", version = "0.0.0" }
serde_json = "1.0.72"

[dev-dependencies]
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
