[package]
name = "graph"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
derivative = "2.2.0"
events = { path = "../events" }
graph-triples = { path = "../graph-triples" }
hash-utils = { path = "../hash-utils" }
kernels = { path = "../kernels" }
num_cpus = "1.13.1"
path-utils = { path = "../path-utils" }
petgraph = { version = "0.6.0", features = ["serde-1"] }
schemars = { version = "0.8.8", features = ["preserve_order"] }
utils = { path = "../utils" }
