api = "0.6"

[buildpack]
id = "stencila/stencila"
version = "0.1.0"
name = "Stencila CLI Buildpack"
keywords = ["stencila"]
homepage = "https://github.com/stencila/stencila/tree/HEAD/rust/buildpack-stencila"

[[buildpack.licenses]]
type = "Apache-2.0"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
