[package]
name = "buildpack-stencila"
description = "A Cloud Native Buildpack for Stencila CLI"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-stencila = { path = "../binary-stencila" }
buildpack = { path = "../buildpack" }
