[package]
name = "parser-prql"
version = "0.0.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
parser-sql = { path = "../parser-sql" }
prql-compiler = "0.2.6"

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
