[package]
name = "stencila-cli"
version = "0.57.0"
edition = "2018"

[[bin]]
name = "stencila"
path = "main.rs"

[features]
open = []
convert = []
serve = []
config = []
plugins = []
upgrade = []
inspect = []
feedback = ["ansi_term", "color-eyre", "indicatif"]
interact = ["ansi_term", "rustyline", "rustyline-derive"]
default = [
    "open",
    "convert",
    "serve",
    "config",
    "plugins",
    "upgrade",
    "inspect",
    "feedback",
    "interact",
]

[dependencies]
ansi_term = {version="0.12.1", optional=true}
color-eyre = {version="0.5.11", optional=true}
exitcode = "1.1.2"
indicatif = { version = "0.16.0", optional = true }
rustyline = { version = "8.0.0", optional = true }
rustyline-derive = { version = "0.4.0", optional = true }
stencila = { path = "../rust" }
structopt = "0.3.21"
