[package]
name = "stencila-cli"
version = "0.55.0"
edition = "2018"

[[bin]]
name = "stencila"
path = "main.rs"

[features]
open = []
convert = []
serve = []
config = []
plugins = []
upgrade = []
inspect = []
interact = ["rustyline", "rustyline-derive"]
default = [
    "open",
    "convert",
    "serve",
    "config",
    "plugins",
    "upgrade",
    "inspect",
    "interact",
]

[dependencies]
ansi_term = "0.12.1"
exitcode = "1.1.2"
stencila = { path = "../rust" }
rustyline = { version = "8.0.0", optional = true }
rustyline-derive = { version = "0.4.0", optional = true }
structopt = "0.3.21"
color-eyre = "0.5.11"
