[package]
name = "stencila-cli"
version = "0.67.1"
edition = "2018"

[[bin]]
name = "stencila"
path = "main.rs"

[features]
feedback = ["ansi_term", "color-eyre", "linya"]
pretty = ["syntect", "termimad"]
interact = ["ansi_term", "rustyline", "rustyline-derive"]
default = ["feedback", "pretty", "interact"]

[dependencies]
ansi_term = { version = "0.12.1", optional = true }
color-eyre = { version = "0.5.11", optional = true }
exitcode = "1.1.2"
linya = { version = "0.1.1", optional = true }
rustyline = { version = "8.2.0", optional = true }
rustyline-derive = { version = "0.4.0", optional = true }
stencila = { path = "../rust" }
structopt = { version = "0.3.21", features = ["wrap_help"] }
syntect = { version = "4.5.0", optional = true }
termimad = { version = "0.10.2", optional = true }
webbrowser = "0.5.5"
