[package]
name = "codec-rmd"
description = "A codec for R Markdown"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = ["codec-md/decode"]
encode = ["codec-md/encode"]

[dependencies]
codec = { path = "../codec", version = "0.0.0" }
codec-md = { path = "../codec-md", version = "0.0.0" }

[dev-dependencies]
test-props = { path = "../test-props", version = "0.0.0" }
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
