[package]
name = "codec-rmd"
description = "A codec for R Markdown"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = ["codec-md/decode"]
encode = ["codec-md/encode"]

[dependencies]
codec = { path = "../codec" }
codec-md = { path = "../codec-md" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
