[package]
name = "codec-html"
description = "A codec for HTML"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = ["kuchiki", "markup5ever"]
encode = [
    "html-escape",
    "mime_guess",
    "node-dispatch",
    "quick-xml",
    "server-next",
    "uuids"
]

[dependencies]

codec = { path = "../codec" }
codec-txt = { path = "../codec-txt" }
node-transform = { path = "../node-transform" }
stencila-schema = { path = "../schema" }

# Dependencies for decode feature
kuchiki = { version = "0.8.1", optional = true }
markup5ever = { version = "0.10.1", optional = true }

# Dependencies for encode feature
html-escape = { version = "0.2.9", optional = true }
mime_guess = { version = "2.0.3", optional = true }
node-dispatch = { path = "../node-dispatch", optional = true }
quick-xml = { version = "0.23.0", optional = true }
server-next = { path = "../server-next", default-features = false, optional = true }
uuids = { path = "../uuids", optional = true }

[dev-dependencies]
reqwest = { version = "0.11.9", features = ["json"] }
test-props = { path = "../test-props" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
