[package]
name = "codec-latex"
description = "A codec for LaTeX"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-pandoc = { path = "../codec-pandoc", version = "0.0.0" }
codec-trait = { path = "../codec-trait", version = "0.0.0" }

[dev-dependencies]
once_cell = "1.8.0"
test-props = { path = "../test-props", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
tokio = { version = "1.13.0", features = ["macros"] }
