[package]
name = "codec-latex"
description = "A codec for LaTeX"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-pandoc = { path = "../codec-pandoc" }
codec = { path = "../codec" }

[dev-dependencies]
test-props = { path = "../test-props" }
test-utils = { path = "../test-utils" }
