[package]
name = "codec-ipynb"
description = "A codec for Jupyter Notebooks"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode", "translate"]
decode = ["codec", "node-coerce", "node-transform", "translate"]
encode = ["codec-html", "codec-md", "codec", "codec-txt"]
translate = ["codec-txt", "node-transform", "strip-ansi-escapes"]

[dependencies]
codec-html = { path = "../codec-html", optional = true }
codec-md = { path = "../codec-md", optional = true }
codec = { path = "../codec", optional = true }
codec-txt = { path = "../codec-txt", optional = true }
node-coerce = { path = "../node-coerce", optional = true }
node-transform = { path = "../node-transform", optional = true }
stencila-schema = { path = "../schema" }
strip-ansi-escapes = { version = "0.1.1", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
