[package]
name = "parser-sql"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
tree-sitter-sql = { git = "https://github.com/nokome/tree-sitter-sql", rev = "6afc167f6ac120727fbc3e0d721e168414f15795" }

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
