[package]
name = "parser-sql"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
stencila-schema = { path = "../schema" }
tree-sitter-sql = { git = "https://github.com/nokome/tree-sitter-sql", rev = "622388189d08a95e22de0f24b987c73fd9946b67" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
