[package]
name = "codec-yaml"
description = "A codec for YAML"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
node-coerce = { path = "../node-coerce" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
