[package]
name = "node-store"
version = "0.0.0"
edition = "2021"

[dependencies]
automerge = "0.3.0"
common = { path = "../common" }
similar = { version = "2.2.1", features = ["unicode"] }
smol_str = "0.1.24"
