version: '3'

includes:
  curl: curl.yaml
  git: git.yaml

vars:
  # Refer to ASDF using full path so that, for example, the `ensure-plugin` task
  # will work straight after the `ensure` task installs asdf (and before PATH is updated)
  ASDF: $HOME/.asdf/bin/asdf

tasks:
  detect:
    desc: Detect which `asdf` tasks are needed for the project
    summary: |
      Adds the `asdf:install` task if there is an `.tool-versions` file in the root of the project.
    ignore_error: true
    silent: true
    cmds:
      - test -f .tool-versions && echo asdf:install >> .stencila/tasks/detected

  ensure:
    desc: Ensure `asdf` is installed
    summary: |
      Checks that `asdf` is installed (and on `PATH`) and installs it using `git` if it is not.
    status:
      - which asdf
    vars:
      VERSION: 0.10.2
    cmds:
      - task: curl:install
      - task: git:install
      - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{.VERSION}}

  ensure-plugin:
    desc: Ensure an `asdf` plugin is installed
    hide: true
    status:
      - '{{.ASDF}} plugin list | grep "^{{.NAME}}$"'
    cmds:
      - task: ensure
      - '{{.ASDF}} plugin add {{.NAME}} {{.URL}}'

  ensure-package:
    desc: Ensure an `asdf` package version is installed
    hide: true
    status:
      # If version specified then can check status, otherwise user
      # wants latest and we need to let `asdf` determine that (slightly slower)
      - |
        if [ "{{.VERSION}}" != "" -a "{{.VERSION}}" != "latest" ]
        then
          asdf list {{.PACKAGE}} {{.VERSION}}
        else
          exit 1
        fi
    cmds:
      - task: ensure-plugin
        vars:
          NAME: '{{.PACKAGE}}'
      - '{{.ASDF}} install {{.PACKAGE}} {{.VERSION | default "latest"}}'

  add:
    desc: Add a tool using `asdf`
    summary: |
      Ensures that the corresponding `asdf` plugin is installed and that
      the tool version is installed.
    status:
      - |
        if [ -n '{{.VERSION}}' ]
        then
          grep '^{{.PACKAGE}} {{.VERSION}}' .tool-versions
        else
          grep '^{{.PACKAGE}} ' .tool-versions
        fi
    cmds:
      - task: ensure-package
        vars:
          PACKAGE: '{{.PACKAGE}}'
          VERSION: '{{.VERSION}}'
      - '{{.ASDF}} local {{.PACKAGE}} {{.VERSION | default "latest"}}'

  remove:
    desc: Remove a tool using `asdf`
    summary: |
      Removes the tool from `.tool-versions` but does not uninstall it
      from the `asdf` directory.
    cmds:
      - sed -i '/{{.PACKAGE}} /d' .tool-versions

  install:
    desc: Install all tools listed in `.tool-versions` using `asdf`
    summary: |
      For each tool listed in `.tool-versions`, ensures that the corresponding `asdf`
      plugin is installed, and that the tool version itself is installed.
    silent: true
    cmds:
      - task: ensure
      - |
        if [ -f .tool-versions ]
        then
          cat .tool-versions | while read LINE 
          do
            {{.ASDF}} plugin add $(echo $LINE | cut -d' ' -f1) || true
          done
        fi
      - '{{.ASDF}} install'
