version: '3'

tasks:
  add:
    desc: Add system packages using Homebrew
    summary: |
      Install the packages specified in variable `PACKAGES` using `brew`.
      At present, does not check whether the packages are installed yet.
    cmds:
      - brew install {{.PACKAGES}}
