version: '3'

includes:
  apt: apt.yaml
  brew: brew.yaml

tasks:
  ensure:
    desc: Ensure Curl is installed
    summary: |
      Checks for `curl` on the `PATH` and installs it if it is not.
    status:
      - which curl
    cmds:
      - task: install-{{OS}}

  ensure-linux:
    desc: Ensure Curl is installed on Debian-based Linux using Apt
    hide: true
    cmds:
      - task: apt:add
        vars:
          PACKAGES: curl

  ensure-darwin:
    desc: Ensure Curl is installed on MacOS using Homebrew
    hide: true
    cmds:
      - task: brew:add
        vars:
          PACKAGES: curl
