version: '3'

includes:
  apt: apt.yaml
  brew: brew.yaml

tasks:
  ensure:
    desc: Ensure that Curl is installed
    summary: |
      Checks for `curl` on the `PATH` and installs it if it is not.
    status:
      - which curl
    cmds:
      - task: install-{{OS}}

  install-linux:
    desc: Install Curl on Debian-based Linux using Apt
    cmds:
      - task: apt:add
        vars:
          PACKAGES: curl

  install-darwin:
    desc: Install Curl on MacOS using Homebrew
    cmds:
      - task: brew:add
        vars:
          PACKAGES: curl
