version: '3'

includes:
  apt: apt.yaml

tasks:
  install:
    desc: Install Git
    summary: |
      Checks for `git` on the `PATH` and installs it if it is not.
    status:
      - which git
    cmds:
      - task: install-{{OS}}

  install-linux:
    desc: Install Git on Debian-based Linux using Apt
    hide: true
    cmds:
      - task: apt:install-packages
        vars:
          PACKAGES: git

  install-darwin:
    desc: Install Git on MacOS using Homebrew
    hide: true
    cmds:
      - task: brew:add
        vars:
          PACKAGES: git
