version: '3'

includes:
  asdf: asdf.yaml

tasks:
  detect:
    desc: Detect which Node.js related tasks are needed
    summary: |
      Adds the `node:install` task if there are any JavaScript files in the
      project (including in subdirectories).
    ignore_error: true
    silent: true
    cmds:
      - test $(find . -type f -iname '*.js' -print -quit) && echo node:install >> .stencila/tasks/detected

  install:
    desc: Install Node.js for the project
    summary: |
      Installs Node.js at the version specified (or latest version none specified). 
      The version installed will be added to `.tool-versions`.
    cmds:
      - task: asdf:add
        vars:
          PACKAGE: nodejs
          VERSION: '{{.VERSION}}'
