version: '3'

includes:
  asdf: asdf.yaml
  python: python.yaml

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true

tasks:
  ensure:
    desc: Require the Poetry package manager for Python
    summary: |
      Checks whether Poetry is installed, and if not, installs it.
    cmds:
      - task: python:ensure
      - task: asdf:add
        vars:
          PACKAGE: poetry

  init:
    desc: Initialize Poetry in a directory
    summary: |
      Checks for a `pyproject.toml` file with a `tool.poetry` section, and if none exists, or it not setup
      for Poetry, runs `poetry init`.
      Ensures that Python is installed in `.tool-version` in the directory.
    status:
      - grep '^\[tool.poetry\]$' pyproject.toml
    silent: true
    cmds:
      - task: python:ensure
      - task: ensure
      - poetry init --no-interaction

  add:
    desc: Add a Python package using Poetry
    cmds:
      - task: init
      - poetry add {{.PACKAGE}}@{{.VERSION | default "latest"}}

  remove:
    desc: Remove a Python package using Poetry
    cmds:
      - task: init
      - poetry remove {{.PACKAGE}}

  install:
    desc: Install all Python packages in `pyproject.toml` using Poetry
    sources:
      - pyproject.toml
    cmds:
      - task: init
      - poetry install

  update:
    desc: Update all Python packages in `pyproject.toml` using Poetry
    cmds:
      - task: init
      - poetry update
