version: '3'

includes:
  asdf: asdf.yaml
  python: python.yaml
  venv: venv.yaml

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true

tasks:
  detect:
    desc: Detect which Poetry related tasks are needed
    summary: |
      Adds the `poetry:install` task if there is a `pyproject.toml` file in the root
      of the project with a `tools.poetry` section.
    ignore_error: true
    cmds:
      - grep '^\[tool.poetry\]$' pyproject.toml && echo poetry:install >> .tasks

  ensure:
    desc: Ensure Poetry is installed
    summary: |
      Checks whether Poetry is installed, and if not, installs it.
    cmds:
      - task: python:install
      - task: asdf:add
        vars:
          PACKAGE: poetry

  init:
    desc: Initialize Poetry in a directory
    summary: |
      Checks for a `pyproject.toml` file with a `tool.poetry` section, and if none exists, or it not setup
      for Poetry, runs `poetry init`.
      Ensures that Python is installed in `.tool-version` in the directory.
    status:
      - grep '^\[tool.poetry\]$' pyproject.toml
    silent: true
    cmds:
      - task: ensure
      - poetry init --no-interaction

  add:
    desc: Add a Python package using Poetry
    cmds:
      - task: ensure
      - task: init
      - task: venv:gitignore
      - poetry add {{.PACKAGE}}@{{.VERSION | default "latest"}}

  remove:
    desc: Remove a Python package using Poetry
    cmds:
      - task: ensure
      - task: init
      - poetry remove {{.PACKAGE}}

  install:
    desc: Install all Python packages in `pyproject.toml` using Poetry
    sources:
      - pyproject.toml
    cmds:
      - task: ensure
      - task: init
      - task: venv:gitignore
      - poetry install

  update:
    desc: Update all Python packages in `pyproject.toml` using Poetry
    cmds:
      - task: ensure
      - task: init
      - task: venv:gitignore
      - poetry update

  clean:
    desc: Delete package installation artifacts created by Poetry
    summary: Removes the `.venv` directory.
    cmds:
      - task: venv:clean

  purge:
    desc: Remove Poetry and associated files from the project
    summary: |
      Removes `poetry` from `.tool-versions` and deletes `poetry.lock` and `.venv`.
      Does NOT delete `pyproject.toml` or remove Poetry sections from it.
    cmds:
      - rm -f poetry.lock
      - task: clean
      - task: asdf:remove
        vars:
          PACKAGE: poetry
