version: '3'

includes:
  apt: apt.yaml
  asdf: asdf.yaml

tasks:
  detect:
    desc: Detect which Python related tasks are needed
    summary: |
      Adds the `python:install` task if there are any Python files in the
      project (including in subdirectories).
    ignore_error: true
    silent: true
    cmds:
      - test $(find . -type f -iname '*.py' -print -quit) && echo python:install >> .stencila/tasks/detected

  install:
    desc: Install Python for the project
    summary: |
      Installs Python at the version specified (or the latest version if none specified). 
      The version installed will be added to the project's `.tool-versions` file.
    cmds:
      - task: install-{{OS}}
        vars:
          VERSION: '{{.VERSION}}'

  install-linux:
    desc: Install Python on Debian-based Linux
    hide: true
    cmds:
      - task: apt:install-packages
        vars:
          # From https://github.com/pyenv/pyenv/wiki#suggested-build-environment
          PACKAGES: >
            make build-essential libssl-dev zlib1g-dev
            libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
            libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
      - task: asdf:add
        vars:
          PACKAGE: python
          VERSION: '{{.VERSION}}'

  install-darwin:
    desc: Install Python on MacOS
    hide: true
    cmds:
      - task: brew:add
        vars:
          # From https://github.com/pyenv/pyenv/wiki#suggested-build-environment
          PACKAGES: openssl readline sqlite3 xz zlib tcl-tk
      - task: asdf:add
        vars:
          PACKAGE: python
          VERSION: '{{.VERSION}}'

  upgrade:
    desc: Upgrade Python to the latest version
    summary: |
      Installs the latest version of Python and adds it to the project's `.tool-versions` file.
    cmds:
      - task: install
        vars:
          VERSION: latest
