version: '3'

includes:
  apt: apt.yaml
  asdf: asdf.yaml

tasks:
  detect:
    desc: Detect which R related tasks are needed
    summary: |
      Adds the `r:install` task if there are any R files in the project (including in subdirectories).
    ignore_error: true
    cmds:
      - test $(find . -type f -iname '*.r' -print -quit) && echo r:install >> .tasks

  install:
    desc: Install R for the project
    cmds:
      - task: install-{{OS}}
        vars:
          VERSION: '{{.VERSION}}'

  install-linux:
    desc: Install R on Debian-based Linux
    hide: true
    cmds:
      - task: apt:install-packages
        vars:
          # From https://github.com/asdf-community/asdf-R#ubuntu--debian
          PACKAGES: >
            build-essential gfortran libbz2-1.0 libbz2-dev libcurl3-dev 
            liblzma-dev liblzma5 libpcre2-dev libreadline-dev xorg-dev
      - task: asdf:add
        vars:
          PACKAGE: R
          VERSION: '{{.VERSION}}'

  install-darwin:
    desc: Install R on MacOS
    hide: true
    cmds:
      - task: brew:add
        vars:
          # From https://github.com/asdf-community/asdf-R#mac
          PACKAGES: gcc xz libxt cairo
      - task: asdf:add
        vars:
          PACKAGE: R
          VERSION: '{{.VERSION}}'
