version: '3'

includes:
  project: project.yaml
  sources: sources.yaml

  apt: apt.yaml
  asdf: asdf.yaml
  brew: brew.yaml
  curl: curl.yaml
  git: git.yaml
  gitignore: gitignore.yaml
  node: node.yaml
  npm: npm.yaml
  pip: pip.yaml
  pnpm: pnpm.yaml
  podman: podman.yaml
  poetry: poetry.yaml
  python: python.yaml
  r: r.yaml
  renv: renv.yaml
  venv: venv.yaml

tasks:
  detect:
    desc: Detect which tasks are required for a project
    silent: true
    cmds:
      - echo "Detecting tasks for $PWD"

      - task: podman:detect

      - task: apt:detect
      - task: asdf:detect

      - task: node:detect
      - task: pnpm:detect

      - task: python:detect
      - task: pip:detect
      - task: poetry:detect

      - task: r:detect
      - task: renv:detect
