version: '3'

desc: Utility tasks

summary: |
  These are mostly very simple tasks, presently mostly used for testing.

tasks:
  sleep:
    desc: Sleep for a specified number of seconds
    cmds:
      - sleep {{.SECONDS | default 1}}

  print-date:
    desc: Print the current date/time
    silent: true
    cmds:
      - echo $(date)
