[package]
name = "tasks"
version = "0.0.0"
edition = "2021"

[features]
default = ["cli"]
cli = ["cli-utils"]

[dependencies]
binary-task = { path = "../binary-task" }
cloud = { path = "../cloud" }
common = { path = "../common" }
cron-utils = { path = "../cron-utils" }
fs2 = "0.4.3"
notify = "4.0.17"
rust-embed = { version = "6.4.0", features = [
    "compression",
    # It can be useful to turn on the `debug-embed` feature so that even in debug mode the 
    # taskfiles are embedded (e.g. when using the debug binary in a container)
    # "debug-embed"
] }

cli-utils = { path = "../cli-utils", optional = true }

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
