[package]
name = "binary-postgrest"
description = "A binary specification for PostgREST (https://github.com/PostgREST/postgrest)"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", features = [
    "download-zip",
    "download-tar-xz"
] }
