[package]
name = "codec-md"
description = "A codec for Markdown"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = ["nom", "pulldown-cmark"]
encode = []

[dependencies]
codec-html = { path = "../codec-html" }
codec = { path = "../codec" }
codec-txt = { path = "../codec-txt" }
formats = { path = "../formats" }
node-coerce = { path = "../node-coerce" }
node-transform = { path = "../node-transform" }
nom = { version = "7.1.0", optional = true }
pulldown-cmark = { version = "0.9.0", optional = true }
json5 = "0.4.1"

[dev-dependencies]
test-props = { path = "../test-props" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
