[package]
name = "buildpack-python"
description = "A Cloud Native Buildpack for Python"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-python = { path = "../binary-python", version = "0.0.0" }
buildpack = { path = "../buildpack", version = "0.0.0" }
