[package]
name = "provider-gdrive"
description = " A provider for Google Drive"
version = "0.0.0"
edition = "2021"

[dependencies]
google-drive = "0.4.0"
provider = { path = "../provider" }
uuids = { path = "../uuids" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
