[package]
name = "provider-gdrive"
description = " A provider for Google Drive"
version = "0.0.0"
edition = "2021"

[dependencies]
google-drive = "0.2.5"
key-utils = { path = "../key-utils", version = "0.0.0" }
provider = { path = "../provider", version = "0.0.0" }
server-utils = { path = "../server-utils", version = "0.0.0" }
uuids = { path = "../uuids", version = "0.0.0" }

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
