[package]
name = "codec-markdown"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-markdown-trait = { path = "../codec-markdown-trait" }
pulldown-cmark = "0.9.3"
