[package]
name = "codec-gdoc"
description = "A codec for Google Docs"
version = "0.0.0"
edition = "2021"

[dependencies]
cloud = { path = "../cloud" }
codec = { path = "../codec" }
codec-pandoc = { path = "../codec-pandoc" }
http-utils = { path = "../http-utils" }
node-address = { path = "../node-address" }
node-transform = { path = "../node-transform" }
provider-gdrive = { path = "../provider-gdrive" }
schemafy = "0.6.0"

# Although these are available via codec::common they seem to be necessary
# as primary dependencies for schemafy
serde = "1.0.137"
serde_json = "1.0.81"

[dev-dependencies]
test-utils = { path = "../test-utils" }
