[package]
name = "codec-gdoc"
description = "A codec for Google Docs"
version = "0.0.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
codec = { path = "../codec", version = "0.0.0" }
futures = { version = "0.3.19", features = ["executor"] }
once_cell = "1.10.0"
regex = "1.5.4"
schemafy = "0.6.0"
serde = "1.0.136"
serde_json = "1.0.79"

[dev-dependencies]
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
