[package]
name = "documents"
description = "Executable documents"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils"]

[dependencies]
codecs = { path = "../codecs" }
common = { path = "../common" }
events = { path = "../events" }
formats = { path = "../formats" }
graph = { path = "../graph" }
graph-triples = { path = "../graph-triples" }
hash-utils = { path = "../hash-utils" }
ignore = "0.4.18"
kernels = { path = "../kernels" }
math-utils = { path = "../math-utils" }
node-address = { path = "../node-address" }
node-dispatch = { path = "../node-dispatch" }
node-patch = { path = "../node-patch" }
node-pointer = { path = "../node-pointer" }
node-query = { path = "../node-query" }
node-reshape = { path = "../node-reshape" }
node-transform = { path = "../node-transform" }
node-validate = { path = "../node-validate" }
notify = "4.0.17"
parser-tailwind = { path = "../parser-tailwind" }
parsers = { path = "../parsers" }
path-utils = { path = "../path-utils" }
providers = { path = "../providers" }
statics = { path = "../statics" }
stencila-schema = { path = "../schema" }
suids = { path = "../suids" }

cli-utils = { path = "../cli-utils", optional = true }

[dev-dependencies]
codec = { path = "../codec" }
codec-md = { path = "../codec-md" }
node-patch = { path = "../node-patch" }
test-utils = { path = "../test-utils" }
# Enable the parser and kernel for any languages used in tests
parsers = { path = "../parsers", features = [
    "parser-calc",
    "parser-r",
    "parser-py",
] }
kernels = { path = "../kernels", features = ["kernel-store", "kernel-calc"] }
