[package]
name = "codec-json"
description = "A codec for JSON"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
node-coerce = { path = "../node-coerce" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
