[package]
name = "codec-json"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

[dev-dependencies]
common-dev = { path = "../common-dev" }
schema = { path = "../schema" }
