[package]
name = "parser-r"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
tree-sitter-r = "0.19.5"

[dev-dependencies]
test-utils = { path = "../test-utils" }
