[package]
name = "codec-json"
description = "A codec for JSON"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-trait = { path = "../codec-trait", version = "0.0.0" }
serde_json = "1.0.68"

[dev-dependencies]
test-props = { path = "../test-props", version = "0.0.0" }
