[package]
name = "codec-json"
description = "A codec for JSON"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-trait = { path = "../codec-trait", version = "0.0.0" }
node-coerce = { path = "../node-coerce", version = "0.0.0" }
serde_json = "1.0.68"

[dev-dependencies]
test-props = { path = "../test-props", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
