[package]
name = "providers"
description = "The set of registered providers, either built-in, or provided by plugins"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils"]

[dependencies]
codecs = { path = "../codecs" }
events = { path = "../events" }
provider = { path = "../provider" }

cli-utils = { path = "../cli-utils", features = ["pretty"], optional = true }

provider-doi = { path = "../provider-doi", optional = true }
provider-elife = { path = "../provider-elife", optional = true }
provider-gdrive = { path = "../provider-gdrive", optional = true }
provider-github = { path = "../provider-github", optional = true }
provider-gitlab = { path = "../provider-gitlab", optional = true }
provider-http = { path = "../provider-http", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils" }
