[package]
name = "providers"
description = "The set of registered providers, either built-in, or provided by plugins"
version = "0.0.0"
edition = "2021"

[features]
cli = ["cli-utils", "structopt", "tokio"]

[dependencies]
provider = { path = "../provider", version = "0.0.0" }
codecs = { path = "../codecs", version = "0.0.0", features = [
    "codec-docx",
    "codec-html",
    "codec-ipynb",
    "codec-json",
    "codec-json5",
    "codec-latex",
    "codec-md",
    "codec-pandoc",
    "codec-pdf",
    "codec-rmd",
    "codec-toml",
    "codec-txt",
    "codec-yaml",
] }
once_cell = "1.8.0"

cli-utils = { path = "../cli-utils", version = "0.0.0", features = [
    "pretty",
], optional = true }
structopt = { version = "0.3.25", optional = true }
tokio = { version = "1.13.0", features = [
    "rt-multi-thread",
    "macros",
], optional = true }

provider-doi = { path = "../provider-doi", version = "0.0.0", optional = true }
provider-elife = { path = "../provider-elife", version = "0.0.0", optional = true }
provider-github = { path = "../provider-github", version = "0.0.0", optional = true }

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
