[package]
name = "node-query"
description = "Query a Stencila document node"
version = "0.0.0"
edition = "2021"

[features]
jsonptr = []
jmespath = ["jmespatch"]
default = ["jsonptr", "jmespath"]

[dependencies]
common = { path = "../common" }
stencila-schema = { path = "../schema" }

jmespatch = { version = "0.3.0", optional = true }
