[package]
name = "kernel-calc"
description = "A kernel that evaluates simple calculator like numerical expressions"
version = "0.0.0"
edition = "2021"

[dependencies]
fasteval = "0.2.4"
kernel = { path = "../kernel" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
