[package]
name = "codec-toml"
description = "A codec for TOML"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
node-coerce = { path = "../node-coerce" }

[dev-dependencies]
test-props = { path = "../test-props" }
test-utils = { path = "../test-utils" }
