[package]
name = "graph-triples"
version = "0.0.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
derivative = "2.2.0"
eyre = "0.6.6"
hash-utils = { path = "../hash-utils", version = "0.0.0" }
path-slash = "0.1.4"
schemars = { version = "0.8.8", features = ["preserve_order"] }
serde = "1.0.130"
serde_json = { version = "1.0.75", features = ["preserve_order"] }
serde_with = "1.11.0"
stencila-schema = { path = "../schema" }
strum = { version = "0.23.0", features = ["derive"] }
