[package]
name = "graph-triples"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
hash-utils = { path = "../hash-utils" }
path-utils = { path = "../path-utils" }
schemars = { version = "0.8.8", features = ["preserve_order"] }
stencila-schema = { path = "../schema" }
