[package]
name = "provider-elife"
description = " A provider for eLife"
version = "0.0.0"
edition = "2021"

[dependencies]
provider = { path = "../provider" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
