[package]
name = "parser-ts"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
parser-js = { path = "../parser-js" }
tree-sitter-typescript = "0.20.1"

[dev-dependencies]
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
