[package]
name = "binary-podman"
description = "A binary specification for Podman (https://github.com/containers/podman)"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", version = "0.0.0", features = [
    "download-zip",
    "download-tar-gz"
] }
