[package]
name = "kernel"
description = "Defines a specification and trait for kernels"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
stencila-schema = { path = "../schema" }
utils = { path = "../utils" }
uuids = { path = "../uuids" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
