[package]
name = "kernel"
description = "Defines a specification and trait for kernels"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
eyre = "0.6.5"
once_cell = "1.8.0"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
stencila-schema = "1.12.0"
strum = { version = "0.23.0", features = ["derive"] }
tracing = "0.1.29"

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
