[package]
name = "kernel"
description = "Defines a specification and trait for kernels"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
parser = { path = "../parser" }
stencila-schema = { path = "../schema" }
utils = { path = "../utils" }
suids = { path = "../suids" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
