[package]
name = "binary-stencila"
description = "A binary specification for Stencila CLI (https://github.com/stencila/stencila)"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", features = [
    "download-zip",
    "download-tar-gz"
] }
