[package]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
name = "stencila"
version = "0.43.3"
authors = ["Stencila <hello@stenci.la>"]
edition = "2018"

[features]
# Compile time feature flags. See https://www.worthe-it.co.za/blog/2018-11-18-compile-time-feature-flags-in-rust.html
# Formats available for `decode` and `encode` methods
json = []
yaml = ["serde_yaml"]
# Languages available for the `query` method
jsonptr = [] #"json-pointer"]
jmespath = [] #"jmespatch"]
# JSON-RPC interface and protocols
request = []
request-stdio = []
request-http = ["reqwest", "jsonwebtoken"]
request-ws = ["tokio-tungstenite", "jsonwebtoken"]
serve = []
serve-stdio = []
serve-http = ["warp", "jsonwebtoken"]
serve-ws = ["warp", "jsonwebtoken"]
# Command line interface
cli = ["structopt", "exitcode"] #, "crossterm"]
# Open a document in the browser
open = ["serve", "serve-http", "serve-ws", "webbrowser"]
# Manage plugins
plugins = ["jsonschema"]
plugins-docker = ["plugins", "bollard"]
plugins-binary = ["plugins", "self_update"]
plugins-package = ["plugins"]
plugins-link = ["plugins"]
# Upgrade the application
upgrade = ["self_update"]
# Configure the application using a TOML file
config = ["humantime", "toml", "validator"]

# All features are on by default, use `--no-default-features --features="json http ..."` to
# cherry pick certain features
default = [
    "json",
    "yaml",
    "jsonptr",
    "jmespath",
    "request",
    "request-stdio",
    "request-http",
    "request-ws",
    "serve",
    "serve-stdio",
    "serve-http",
    "serve-ws",
    "cli",
    "open",
    "plugins",
    "plugins-docker",
    "plugins-binary",
    "plugins-package",
    "plugins-link",
    "upgrade",
    "config",
]

[dependencies]
anyhow = "1.0.38"
bollard = { version = "0.10.1", optional = true }
chrono = "0.4.19"
dirs-next = "2.0.0"
env_logger = "0.8.3"
exitcode = { version = "1.1.2", optional = true }
futures = "0.3.13"
humantime = { version = "2.1.0", optional = true }
jsonschema = { version = "0.6.0", optional = true }
jsonwebtoken = { version = "7.2.0", optional = true }
once_cell = "1.7.2"
rand = "0.8.3"
regex = "1.4.5"
reqwest = { version = "0.11.2", optional = true, features = ["json"] }
self_update = { version = "0.26.0", optional = true, features = [
    "archive-tar",
    "archive-zip",
    "compression-flate2",
    "compression-zip-deflate",
] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = { version = "1.0.64" }
serde_yaml = { version = "0.8.17", optional = true }
structopt = { version = "0.3.21", optional = true }
strum = { version = "0.20", features = ["derive"] }
strum_macros = "0.20.1"
thiserror = "1.0.24"
tokio = { version = "1.3.0", features = ["full"] }
tokio-tungstenite = { version = "0.14.0", optional = true }
toml = { version = "0.5.8", optional = true }
tracing = "0.1.25"
url = "2.2.1"
validator = { version = "0.13.0", features = ["derive"], optional = true}
warp = { version = "0.3.0", optional = true }
webbrowser = { version = "0.5.5", optional = true }

[dev-dependencies]
pretty_assertions = "0.7.1"
