[package]
name = "stencila-node"
version = "0.87.0"
description = "Stencila in Node.js"
authors = ["Nokome Bentley <nokome@stenci.la>"]
license = "Apache-2.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stencila = { path = "../rust" }
neon = { version = "0.8.3", default-features = false, features = ["napi-6", "event-queue-api"] }
