[package]
name = "kernel-store"
version = "0.0.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel", version = "0.0.0" }

[dev-dependencies]
tokio = { version = "1.12.0", features = ["rt", "macros"] }
