[package]
name = "codec-pandoc"
description = "A codec for Pandoc JSON"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = ["codec-txt", "node-coerce"]
encode = ["node-transform"]

[dependencies]
binaries = { path = "../binaries" }
cloud = { path = "../cloud" }
codec = { path = "../codec" }
codec-json = { path = "../codec-json" }
codec-rpng = { path = "../codec-rpng" }
formats = { path = "../formats" }
key-utils = { path = "../key-utils" }
node-dispatch = { path = "../node-dispatch" }
pandoc_types = "0.5.0"
path-utils = { path = "../path-utils" }
uuids = { path = "../uuids" }

codec-txt = { path = "../codec-txt", optional = true }
node-coerce = { path = "../node-coerce", optional = true }
node-transform = { path = "../node-transform", optional = true }

[dev-dependencies]
test-props = { path = "../test-props" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
