[package]
name = "binary-node"
description = "A binary specification for Node.js"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", features = [
    "download-zip",
    "download-tar-gz",
    "download-tar-xz",
] }
