[package]
name = "codec-date"
description = "A codec for `Date` nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
dtparse = "1.2.0"

[dev-dependencies]
test-utils = { path = "../test-utils" }
