[package]
name = "codec-date"
description = "A codec for `Date` nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
codec = { path = "../codec", version = "0.0.0" }
dtparse = "1.2.0"

[dev-dependencies]
test-utils = { path = "../test-utils", version = "0.0.0" }
