[package]
name = "stencila-python"
version = "0.78.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stencila = { path = "../rust" }
pyo3 = { version = "0.13.2", features = ["extension-module"] }
