api = "0.6"

[buildpack]
id = "stencila/dockerfile"
version = "0.1.0"
name = "Stencila Dockerfile Buildpack"
keywords = ["docker", "dockerfile", "containerfile"]
homepage = "https://github.com/stencila/stencila/tree/HEAD/rust/buildpack-dockerfile"

[[buildpack.licenses]]
type = "Apache-2.0"

[metadata]
creates-layer = false

# Does not build or run on any stucks but we have to 
# have something here to meet spec
[[stacks]]
id = "none"
