[package]
name = "buildpack-dockerfile"
description = "A buildpack for Dockerfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-podman = { path = "../binary-podman" }
buildpack = { path = "../buildpack" }
