[package]
name = "http-utils"
description = "Convenience functions for making requests over HTTP"
version = "0.0.0"
edition = "2021"

[dependencies]
dirs = "4.0.0"
eyre = "0.6.5"
http-cache-reqwest = "0.3.0"
once_cell = "1.9.0"
reqwest = { version = "0.11.9", features = ["json", "native-tls-vendored"] }
reqwest-middleware = "0.1.5"
serde_json = "1.0.75"
tempfile = "3.2.0"
tokio = { version = "1.13.0" }
