[package]
name = "http-utils"
description = "Convenience functions for making requests over HTTP"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
http = "0.2.8"
http-cache-reqwest = "0.4.5"
reqwest = { version = "0.11.9", features = ["json", "native-tls-vendored"] }
reqwest-middleware = "0.1.5"
url = "2.2.2"
urlencoding = "2.1.0"
