[package]
name = "codec-txt"
description = "A codec for plain text"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
node-coerce = { path = "../node-coerce" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
