[package]
name = "formats"
description = "Metadata on file formats"
version = "0.0.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
once_cell = "1.8.0"
schemars = "0.8.6"
serde = "1.0.130"
serde_json = "1.0.68"
serde_with = "1.11.0"
