[package]
name = "parser-rust"
version = "0.0.0"
edition = "2021"

[dependencies]
parser-treesitter = { path = "../parser-treesitter" }
tree-sitter-rust = { version = "0.20.0" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
