[package]
name = "codec-md"
description = "A codec for Markdown"
version = "0.0.0"
edition = "2021"

[features]
default = ["decode", "encode"]
decode = []
encode = []

[dependencies]
codec-html = { path = "../codec-html", version = "0.0.0" }
codec-trait = { path = "../codec-trait", version = "0.0.0" }
codec-txt = { path = "../codec-txt", version = "0.0.0" }
itertools = "0.10.1"
node-coerce = { path = "../node-coerce", version = "0.0.0" }
node-transform = { path = "../node-transform", version = "0.0.0" }
nom = "7.0.0"
once_cell = "1.8.0"
pulldown-cmark = "0.8.0"
regex = "1.5.4"
serde_json = "1.0.68"
serde_yaml = "0.8.21"
stencila-schema = "1.12.0"
tracing = "0.1.29"

[dev-dependencies]
test-props = { path = "../test-props", version = "0.0.0" }
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
tokio = { version = "1.13.0", features = ["macros"] }
