[package]
name = "parser-treesitter"
version = "0.0.0"
edition = "2021"

[dependencies]
graph-triples = { path = "../graph-triples", version = "0.0.0" }
parser = { path = "../parser", version = "0.0.0" }
tree-sitter = "0.19.5"
