# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "stencila"
version = "0.123.0"
authors = ["Stencila <hello@stenci.la>"]
edition = "2018"

# Compile time feature flags. See https://www.worthe-it.co.za/blog/2018-11-18-compile-time-feature-flags-in-rust.html
# All features are on by default, use `--no-default-features --features="json http ..."` to
# cherry pick certain features.
# Our use of features is somewhat over the top but should hopefully allow us to create more
# minimal binaries as needed (e.g. for creating really small container images).

[features]

clis = ["cli", "structopt", "binaries/cli", "binaries/structopt"]
clis-pretty = ["cli/pretty"]
clis-progress = ["cli/progress"]
clis-interact = ["cli/interact"]

serve = []
serve-stdio = ["serve"]
serve-http = ["serve", "sudo", "warp", "jsonwebtoken", "rust-embed"]
serve-ws = ["serve-http"]

request = []
request-docker = ["bollard"]
request-http = ["reqwest", "jsonwebtoken"]
request-stdio = []
request-ws = ["tokio-tungstenite", "jsonwebtoken"]

plugins = ["jsonschema", "semver"]
plugins-binary = ["plugins", "self_update"]
plugins-docker = ["plugins", "bollard"]
plugins-javascript = ["plugins"]
plugins-link = ["plugins"]
plugins-python = ["plugins"]
plugins-r = ["plugins"]

kernels-calc = ["fasteval"]
kernels-jupyter = ["zmq/vendored"]

upgrade = ["self_update"]

import-elife = ["minidom"]
import-github = []

decode-date = ["codec-trait", "codec-date"]
decode-docx = ["decode-pandoc"]
decode-html = ["codec-trait", "codec-html"]
decode-ipynb = ["codec-trait", "codec-ipynb"]
decode-json = ["codec-trait", "codec-json"]
decode-json5 = ["codec-trait", "codec-json5"]
decode-latex = ["decode-pandoc"]
decode-md = ["codec-trait", "codec-md"]
decode-pandoc = ["node-transform", "binaries", "pandoc_types"]
decode-person = ["codec-trait", "codec-person"]
decode-rmd = ["codec-trait", "codec-rmd"]
decode-rpng = ["png"]
decode-toml = ["codec-trait", "codec-toml"]
decode-txt = ["codec-trait", "codec-txt"]
decode-yaml = ["codec-trait", "codec-yaml"]

encode-docx = ["encode-pandoc"]
encode-ipynb = ["codec-trait", "codec-ipynb"]
encode-json = ["codec-trait", "codec-json"]
encode-json5 = ["codec-trait", "codec-json5"]
encode-latex = ["encode-pandoc"]
encode-md = ["codec-trait", "codec-md"]
encode-pandoc = ["node-transform", "binaries", "pandoc_types"]
encode-pdf = ["chromiumoxide"]
encode-png = ["chromiumoxide"]
encode-rmd = ["codec-trait", "codec-rmd"]
encode-rpng = ["encode-png", "png"]
encode-toml = ["codec-trait", "codec-toml"]
encode-yaml = ["codec-trait", "codec-yaml"]

coerce = ["node-coerce"]

reshape = ["decode-date", "decode-person"]

compile-calc = []
compile-js = ["tree-sitter", "tree-sitter-javascript"]
compile-py = ["tree-sitter", "tree-sitter-python"]
compile-r = ["tree-sitter", "tree-sitter-r"]
compile-ts = ["tree-sitter", "tree-sitter-javascript", "tree-sitter-typescript"]

query-jmespath = ["jmespatch"]
query-jsonptr = []

default = [
  "clis",
  "clis-progress",
  "clis-pretty",
  "clis-interact",
  "serve",
  "serve-stdio",
  "serve-http",
  "serve-ws",
  "request",
  "request-docker",
  "request-http",
  "request-stdio",
  "request-ws",
  "binaries",
  "plugins",
  "plugins-binary",
  "plugins-docker",
  "plugins-link",
  "plugins-javascript",
  "plugins-python",
  "plugins-r",
  "kernels-calc",
  "kernels-jupyter",
  "upgrade",
  "import-elife",
  "import-github",
  "decode-date",
  "decode-docx",
  "decode-html",
  "decode-ipynb",
  "decode-json",
  "decode-json5",
  "decode-latex",
  "decode-md",
  "decode-pandoc",
  "decode-person",
  "decode-rmd",
  "decode-rpng",
  "decode-toml",
  "decode-txt",
  "decode-yaml",
  "encode-docx",
  "encode-ipynb",
  "encode-json",
  "encode-json5",
  "encode-latex",
  "encode-md",
  "encode-pandoc",
  "encode-pdf",
  "encode-png",
  "encode-rmd",
  "encode-rpng",
  "encode-toml",
  "encode-yaml",
  "coerce",
  "reshape",
  "compile-calc",
  "compile-js",
  "compile-py",
  "compile-r",
  "compile-ts",
  "query-jsonptr",
  "query-jmespath",
  "webbrowser",
  "structopt",
]

[dependencies]
ansi_term = { version = "=0.12.1", optional = true }
async-recursion = "0.3.2"
async-trait = "=0.1.51"
base64 = "=0.13.0"
bollard = { version = "=0.11.0", optional = true }
chromiumoxide = { version = "=0.3.1", optional = true, features = [
  "tokio-runtime",
] }
chrono = { version = "=0.4.19", features = ["serde"] }
color-eyre = { version = "=0.5.11", optional = true }
crossbeam-channel = "=0.5.1"
defaults = "=0.2.0"
derivative = "=2.2.0"
derive_more = "0.99.16"
dirs-next = "=2.0.0"
enum_dispatch = "=0.3.7"
exitcode = "=1.1.2"
eyre = "=0.6.5"
fasteval = { version = "=0.2.4", optional = true }
futures = "=0.3.17"
gitignore = "=1.0.7"
glob = "=0.3.0"
handlebars = "=4.1.3"
hex = "0.4.3"
hmac = "0.11.0"
humantime = "=2.1.0"
ignore = "=0.4.18"
Inflector = "0.11.4"
itertools = "0.10.1"
jmespatch = { version = "=0.3.0", optional = true }
json5 = "=0.4.1"
jsonschema = { version = "=0.12.2", optional = true }
jsonwebtoken = { version = "=7.2.0", optional = true }
lexiclean = "=0.0.1"
maplit = "=1.0.2"
mime_guess = "=2.0.3"
minidom = { version = "=0.13.0", optional = true }
nanoid = "=0.4.0"
notify = "=4.0.17"
once_cell = "=1.8.0"
pandoc_types = { version = "=0.4.0", optional = true }
path-slash = "=0.1.4"
pathdiff = "=0.2.1"
petgraph = { version = "=0.6.0", features = ["serde-1"] }
png = { version = "=0.17.2", optional = true }
portpicker = "0.1.1"
rand = "=0.8.4"
regex = "=1.5.4"
reqwest = { version = "=0.11.6", optional = true, features = ["json"] }
rust-embed = { version = "=6.2.0", features = ["compression"], optional = true }
schemars = { version = "=0.8.6", features = ["preserve_order", "chrono"] }
self_update = { version = "=0.27.0", optional = true, features = [
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
] }
semver = { version = "=1.0.4", optional = true }
serde = { version = "=1.0.130", features = ["derive", "rc"] }
serde_json = { version = "=1.0.68", features = ["preserve_order"] }
serde_with = "=1.11.0"
serde_yaml = "=0.8.21"
sha2 = "0.9.8"
similar = { version = "=2.1.0", features = ["unicode"] }
slug = "=0.1.4"
stencila-schema = "=1.12.0"
structopt = { version = "=0.3.25", features = ["wrap_help"], optional = true }
strum = { version = "=0.22.0", features = ["derive"] }
strum_macros = "=0.22.0"
sudo = { version = "=0.6.0", optional = true }
tar = { version = "=0.4.37", optional = true }
tempfile = "3.2.0"
thiserror = "=1.0.30"
tokio = { version = "1.12.0", features = ["full"] }
tokio-stream = "=0.1.7"
tokio-tungstenite = { version = "=0.15.0", optional = true }
toml = "=0.5.8"
tracing = "=0.1.29"
tracing-appender = "=0.1.2"
tracing-error = "=0.1.2"
tracing-serde = "=0.1.2"
tracing-subscriber = "=0.2.25"
tree-sitter = { version = "=0.19.5", optional = true }
tree-sitter-javascript = { version = "=0.19.0", optional = true }
tree-sitter-python = { version = "=0.19.0", optional = true }
tree-sitter-r = { version = "=0.19.3", optional = true }
tree-sitter-typescript = { version = "=0.19.0", optional = true }
unicode-segmentation = "=1.8.0"
url = "=2.2.2"
urlencoding = "2.1.0"
validator = { version = "=0.14.0", features = ["derive"] }
warp = { version = "=0.3.1", optional = true }
webbrowser = { version = "=0.5.5", optional = true }
zmq = { version = "=0.9.2", optional = true, default-features = false }

binaries = { path = "../binaries", version = "0.0.0", optional = true }
cli = { path = "../cli", version = "0.0.0", optional = true }
codec-date = { path = "../codec-date", version = "0.0.0", optional = true }
codec-html = { path = "../codec-html", version = "0.0.0", optional = true }
codec-ipynb = { path = "../codec-ipynb", version = "0.0.0", optional = true }
codec-json = { path = "../codec-json", version = "0.0.0", optional = true }
codec-json5 = { path = "../codec-json5", version = "0.0.0", optional = true }
codec-md = { path = "../codec-md", version = "0.0.0", optional = true }
codec-person = { path = "../codec-person", version = "0.0.0", optional = true }
codec-rmd = { path = "../codec-rmd", version = "0.0.0", optional = true }
codec-toml = { path = "../codec-toml", version = "0.0.0", optional = true }
codec-trait = { path = "../codec-trait", version = "0.0.0", optional = true }
codec-txt = { path = "../codec-txt", version = "0.0.0", optional = true }
codec-yaml = { path = "../codec-yaml", version = "0.0.0", optional = true }
node-coerce = { path = "../node-coerce", version = "0.0.0", optional = true }
node-transform = { path = "../node-transform", version = "0.0.0", optional = true }

[dev-dependencies]
criterion = "0.3.5"
insta = { version = "1.8.0", features = ["glob"] }
pretty_assertions = "1.0.0"
proptest = "1.0.0"

[[bench]]
harness = false
name = "compile_code"
