[package]
name = "codec-rpng"
description = "A codec for reproducible PNG images"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-json = { path = "../codec-json" }
codec-png = { path = "../codec-png" }
codec = { path = "../codec" }
png = "0.17.2"

[dev-dependencies]
test-props = { path = "../test-props" }
test-utils = { path = "../test-utils" }
