[package]
name = "node-patch"
description = "Diffing, patching, and merging for Stencila document nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
codecs = { path = "../codecs", version = "0.0.0" }
codec-html = { path = "../codec-html", version = "0.0.0" }
codec-txt = { path = "../codec-txt", version = "0.0.0" }
defaults = "0.2.0"
derive_more = "0.99.17"
eyre = "0.6.5"
itertools = "0.10.3"
node-address = { path = "../node-address", version = "0.0.0" }
node-coerce = { path = "../node-coerce", version = "0.0.0" }
node-dispatch = { path = "../node-dispatch", version = "0.0.0" }
node-pointer = { path = "../node-pointer", version = "0.0.0" }
schemars = { version = "=0.8.8", features = ["preserve_order", "chrono"] }
serde = "1.0.130"
serde_json = "1.0.72"
serde_with = "1.11.0"
similar = { version = "=2.1.0", features = ["unicode"] }
stencila-schema = "1.14.0" 
strum = { version = "0.23.0", features = ["derive"] }
tracing = "0.1.29"
unicode-segmentation = "=1.8.0"
thiserror = "1.0.30"

[dev-dependencies]
test-props = { path = "../test-props", version = "0.0.0" }
test-snaps = { path = "../test-snaps", version = "0.0.0" }
test-utils = { path = "../test-utils", version = "0.0.0" }
