[package]
name = "node-patch"
description = "Diffing, patching, and merging for Stencila document nodes"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
defaults = "0.2.0"
derive_more = "0.99.17"
eyre = "0.6.5"
itertools = "0.10.3"
schemars = "0.8.8"
serde = "1.0.130"
serde_with = "1.11.0"
similar = "2.1.0"
stencila-schema = "1.12.0"
strum = "0.23.0"
