[package]
name = "node-patch"
description = "Diffing, patching, and merging for Stencila document nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
codec-html = { path = "../codec-html" }
codec-txt = { path = "../codec-txt" }
codecs = { path = "../codecs" }
common = { path = "../common" }
flagset = "0.4.3"
node-address = { path = "../node-address" }
node-coerce = { path = "../node-coerce" }
node-dispatch = { path = "../node-dispatch" }
node-pointer = { path = "../node-pointer" }
schemars = { version = "0.8.8", features = ["preserve_order", "chrono"] }
similar = { version = "2.1.0", features = ["unicode"] }
stencila-schema = { path = "../schema" }
suids = { path = "../suids" }
thiserror = "1.0.31"
unicode-segmentation = "1.9.0"

[dev-dependencies]
criterion = "0.4.0"
test-props = { path = "../test-props" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }

[[bench]]
name = "value"
harness = false
