[package]
name = "codec-json5"
description = "A codec for JSON5"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
json5 = "0.4.1"
node-coerce = { path = "../node-coerce" }

[dev-dependencies]
test-props = { path = "../test-props" }
test-utils = { path = "../test-utils" }
