[package]
name = "files"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
events = { path = "../events" }
formats = { path = "../formats" }
gitignore = "1.0.7"
ignore = "0.4.18"
schemars = { version = "0.8.8", features = ["preserve_order", "chrono"] }
