[package]
name = "files"
version = "0.0.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.2"
defaults = "0.2.0"
events = { path = "../events", version = "0.0.0" }
formats = { path = "../formats", version = "0.0.0" }
gitignore = "1.0.7"
ignore = "0.4.18"
schemars = { version = "0.8.8", features = ["preserve_order", "chrono"] }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_with = "1.11.0"
strum = { version = "0.23.0", features = ["derive"] }
