[package]
name = "kernel-zsh"
description = "A microkernel for Zsh"
version = "0.0.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel" }
kernel-micro = { path = "../kernel-micro" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
