[package]
name = "kernel-postgrest"
description = "A kernel that make PostgREST requests"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-postgrest = { path = "../binary-postgrest" }
kernel = { path = "../kernel" }
kernel-http = { path = "../kernel-http" }
parser-postgrest = { path = "../parser-postgrest" }
