[package]
name = "schema-gen"
version = "0.0.0"
edition = "2021"

[features]
default = ["docs"]
docs = ["codec", "codec-markdown", "schema"]

[dependencies]
codec = { path = "../codec", optional = true }
codec-markdown = { path = "../codec-markdown", optional = true }
common = { path = "../common" }
schema = { path = "../schema", optional = true }
schemars = { version = "0.8.13", features = ["indexmap2"] }
