[package]
edition = "2021"
name = "kernels"
version = "0.0.0"

[features]
default = ["kernel-store", "kernel-micro"]
cli = ["cli-utils", "events"]

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
humantime = { version = "2.1.0" }
parsers = { path = "../parsers" }
kernel = { path = "../kernel" }

# For `cli` feature
cli-utils = { path = "../cli-utils", optional = true }
events = { path = "../events", optional = true }

# For `kernel-*` features
kernel-bash = { path = "../kernel-bash", optional = true }
kernel-calc = { path = "../kernel-calc", optional = true }
kernel-http = { path = "../kernel-http", optional = true }
kernel-micro = { path = "../kernel-micro", optional = true }
kernel-node = { path = "../kernel-node", optional = true }
kernel-postgrest = { path = "../kernel-postgrest", optional = true }
kernel-python = { path = "../kernel-python", optional = true }
kernel-r = { path = "../kernel-r", optional = true }
kernel-sql = { path = "../kernel-sql", optional = true }
kernel-store = { path = "../kernel-store", optional = true }
kernel-tailwind = { path = "../kernel-tailwind", optional = true }
kernel-zsh = { path = "../kernel-zsh", optional = true }
