[package]
edition = "2021"
name = "kernels"
version = "0.0.0"

[features]
default = ["kernel-store", "kernel-micro"]
cli = ["cli-utils", "events", "parsers", "structopt"]

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
graph-triples = { path = "../graph-triples" }
humantime = { version = "2.1.0" }
kernel = { path = "../kernel" }

# For `cli` feature
cli-utils = { path = "../cli-utils", optional = true }
events = { path = "../events", optional = true }
parsers = { path = "../parsers", optional = true }
structopt = { version = "0.3.25", optional = true }

# For `kernel-*` features
kernel-bash = { path = "../kernel-bash", optional = true }
kernel-calc = { path = "../kernel-calc", optional = true }
kernel-deno = { path = "../kernel-deno", optional = true }
kernel-jupyter = { path = "../kernel-jupyter", optional = true }
kernel-micro = { path = "../kernel-micro", optional = true }
kernel-node = { path = "../kernel-node", optional = true }
kernel-python = { path = "../kernel-python", optional = true }
kernel-r = { path = "../kernel-r", optional = true }
kernel-store = { path = "../kernel-store", optional = true }
kernel-zsh = { path = "../kernel-zsh", optional = true }
