[package]
edition = "2021"
name = "kernels"
version = "0.0.0"

[features]
default = ["store"]

cli = ["cli-utils", "parsers", "once_cell", "structopt", "tokio"]

calc = ["kernel-calc"]
store = ["kernel-store"]

micro = ["kernel-micro"]
bash = ["kernel-bash", "micro"]
node = ["kernel-node", "micro"]
python = ["kernel-python", "micro"]
r = ["kernel-r", "micro"]

jupyter = ["kernel-jupyter"]

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
derive_more = "0.99.17"
graph-triples = { path = "../graph-triples", version = "0.0.0" }
kernel = { path = "../kernel", version = "0.0.0" }
serde = "1.0.130"
serde_json = "1.0.72"
tracing = "0.1.29"
validator = "0.14.0"

cli-utils = { path = "../cli-utils", version = "0.0.0", optional = true }
once_cell = { version = "1.8.0", optional = true }
parsers = { path = "../parsers", version = "0.0.0", optional = true }
structopt = { version = "0.3.25", optional = true }
tokio = { version = "1.13.0", optional = true }

kernel-bash = { path = "../kernel-bash", version = "0.0.0", optional = true }
kernel-calc = { path = "../kernel-calc", version = "0.0.0", optional = true }
kernel-jupyter = { path = "../kernel-jupyter", version = "0.0.0", optional = true }
kernel-micro = { path = "../kernel-micro", version = "0.0.0", optional = true }
kernel-node = { path = "../kernel-node", version = "0.0.0", optional = true }
kernel-python = { path = "../kernel-python", version = "0.0.0", optional = true }
kernel-r = { path = "../kernel-r", version = "0.0.0", optional = true }
kernel-store = { path = "../kernel-store", version = "0.0.0", optional = true }
