[package]
name = "node-execute"
description = "Compile and execute Stencila document nodes"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
formats = { path = "../formats" }
graph = { path = "../graph" }
graph-triples = { path = "../graph-triples" }
kernels = { path = "../kernels" }
node-address = { path = "../node-address" }
node-dispatch = { path = "../node-dispatch" }
node-patch = { path = "../node-patch" }
node-pointer = { path = "../node-pointer" }
node-validate = { path = "../node-validate" }
parsers = { path = "../parsers" }
path-utils = { path = "../path-utils" }
stencila-schema = { path = "../schema" }
uuids = { path = "../uuids" }

[dev-dependencies]
codec = { path = "../codec" }
codec-md = { path = "../codec-md" }
node-patch = { path = "../node-patch" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
# Enable the parser and kernel for any languages used in tests
parsers = { path = "../parsers", features = ["parser-calc", "parser-r", "parser-py"] }
kernels = { path = "../kernels", features = ["kernel-store", "kernel-calc"] }
