[package]
name = "stencila-r"
version = "1.0.5"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stencila = { path = "../rust" }
extendr-api = { git = "https://github.com/extendr/extendr" } 
