[package]
name = "provider-github"
description = " A provider for GitHub"
version = "0.0.0"
edition = "2021"

[dependencies]
octocrab = "0.13.0"
provider = { path = "../provider", version = "0.0.0" }

[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros"] }
