[package]
name = "provider-github"
description = " A provider for GitHub"
version = "0.0.0"
edition = "2021"

[dependencies]
archive-utils = { path = "../archive-utils", features = [
    "tar-gz",
] }
octorust = "0.1.35"
provider = { path = "../provider" }
uuids = { path = "../uuids" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
