[package]
name = "provider-http"
description = " A provider for HTTP resources"
version = "0.0.0"
edition = "2021"

[dependencies]
archive-utils = { path = "../archive-utils", features = [
    "tar",
    "tar-gz",
    "tar-xz",
    "zip",
] }
cron-utils = { path = "../cron-utils" }
provider = { path = "../provider" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
