# Workflow to check that the build succeeds and build and commit generated files
#
# Note that actual release builds are done on tags by the `release.yml` workflow.
# This just provides a check to increase the likelihood that the release
# workflow will be successful.

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUST_VERSION: "1.71.0"
  CARGO_TERM_COLOR: always
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update ${{ env.RUST_VERSION }} --no-self-update && rustup default ${{ env.RUST_VERSION }}

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build CLI and packages
        run: make build

      - name: Build generated files
        run: make generated

      - name: Commit any changes to generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(*): Update generated files"
