# Workflow for testing installation of various products
#
# Triggered after a release and performed on separate VMs to the
# build so as to test independence from repo checkout and build dependencies.
#
# The intent of this workflow is to quickly identify any issues with
# releases so that a new release can be made if necessary.

name: Install

on:
  # Allow this workflow to be triggered by the `release.yml` workflow
  # or manually at https://github.com/stencila/stencila/actions/workflows/install.yml
  workflow_dispatch:
    inputs:
      cli:
        description: Install CLI
        type: boolean
        default: true
      docker:
        description: Run Docker image
        type: boolean
        default: true
      node:
        description: Install Node SDK
        type: boolean
        default: true
      python:
        description: Install Python SDK
        type: boolean
        default: true

jobs:
  cli:
    if: ${{ inputs.cli }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install CLI
        run: curl --proto '=https' --tlsv1.2 -sSf https://stencila.dev/install.sh | sh

      - name: Run CLI
        run: stencila --version

  docker:
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull stencila/stencila

      - name: Run image
        run: docker run --rm stencila/stencila --help

  node:
    if: ${{ inputs.node }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          - 18
          - 20
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install package
        run: npm install @stencila/node

      - name: Import package
        run: node -e 'import("@stencila/node").then(console.log).catch((error) => {console.error(error); process.exit(1)})'

  python:
    if: ${{ inputs.python }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          # These must be strings to avoid rounding down e.g. 3.10 -> 3.1
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install package
        run: python3 -m pip install stencila

      - name: Import package
        run: python3 -c 'import stencila'
