# Workflow for linting and testing

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

env:
  RUST_VERSION: '1.71.0'
  CARGO_TERM_COLOR: always

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Rust
        run: rustup update ${{ env.RUST_VERSION }} --no-self-update && rustup default ${{ env.RUST_VERSION }} && rustup component add clippy

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: make lint

      - name: Test
        run: make test
