[package]
edition = "2021"
name = "codec-script"
version = "0.1.0"

[dependencies]
codec = { path = "../codec" }
codec-md = { path = "../codec-md" }
common = { path = "../common" }
formats = { path = "../formats" }
node-pointer = { path = "../node-pointer" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
