[package]
edition = "2021"
name = "codec-script"
version = "0.1.0"

[dependencies]
codec = { path = "../codec" }
codec-md = { path = "../codec-md" }
common = { path = "../common" }

[dev-dependencies]
test-props = { path = "../test-props" }
test-snaps = { path = "../test-snaps" }
test-utils = { path = "../test-utils" }
