[package]
name = "node-reshape"
description = "Reshape a Stencila document by detecting, inferring, or guessing properties and content"
version = "0.0.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
codec-date = { path = "../codec-date" }
codec-person = { path = "../codec-person" }
codec-txt = { path = "../codec-txt" }
common = { path = "../common" }
stencila-schema = { path = "../schema" }
utils = { path = "../utils" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
