api = "0.6"

[buildpack]
id = "stencila/apt"
version = "0.1.0"
name = "Stencila apt Packages Buildpack"
description = "Installs apt packages"
keywords = ["apt", "packages", "ubuntu"]
homepage = "https://github.com/stencila/stencila/tree/HEAD/rust/buildpack-apt"

[[buildpack.licenses]]
type = "Apache-2.0"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
