[package]
name = "buildpack-apt"
description = "A Cloud Native Buildpack for apt packages"
version = "0.0.0"
edition = "2021"

[dependencies]
binary = { path = "../binary", features = ["download"] }
buildpack = { path = "../buildpack" }
sys-info = "0.9.1"
utils = { path = "../utils" }
