[package]
name = "buildpack-r"
description = "A Cloud Native Buildpack for R"
version = "0.0.0"
edition = "2021"

[dependencies]
binaries = { path = "../binaries", version = "0.0.0", features = ["binary-r"] }
buildpack = { path = "../buildpack", version = "0.0.0" }
