[package]
name = "buildpack-r"
description = "A Cloud Native Buildpack for R"
version = "0.0.0"
edition = "2021"

[dependencies]
binary-r = { path = "../binary-r", version = "0.0.0" }
buildpack = { path = "../buildpack", version = "0.0.0" }
buildpack-apt = { path = "../buildpack-apt", version = "0.0.0" }
serde_json = "1.0.75"
sys-info = "0.9.1"
